name: Deploy to ECS Fargate

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      run: |
        echo ${{ secrets.AWS_ACCESS_KEY_ID }} >> $GITHUB_ENV
        echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} >> $GITHUB_ENV
        echo ${{ secrets.AWS_REGION }} >> $GITHUB_ENV
      shell: bash

    - name: Deploy to ECS Fargate
      run: |
        aws ecs update-service --cluster my-cluster --service my-first-service --force-new-deployment
      shell: bash
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
